### ISSUE TITLE
make production ending semicolon optional

### ISSUE THREAD

**Issue by CrockAgile** [snewt/bnf#14]
Plenty of BNF examples, including the [wikipedia example](https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form#Example), do not require productions to terminate with a semicolon, but rather only require a newline. I believe the parser could be updated to optionally use the ending semicolon, which would support both formats.

**Comment by snewt** [comment]
Yeah I've been thinking about this one too. Thanks for raising it.

**Comment by snewt** [comment]
One note, I'd like it if we didn't require a newline either so breaking up long productions or expressions across lines wouldn't prohibit parsing.

**Comment by CrockAgile** [comment]
Not requiring the newline seems trickier to me, but sounds like you have an idea. How would that work?

**Comment by snewt** [comment]
@CrockAgile I've got a lot of faith it what we can get out of `nom`, I could be misguided but here's my general thought. Productions can end on a `;` on `eof` or if with peek or some similar custom mechanism we are able to see that a `<...> ::=` is next in line. What do you think?

**Comment by CrockAgile** [comment]
@snewt that seems reasonable to me. I still need to brush up on nom to know how it handles forward peeking, but you are probably right it is doable. I would guess it would improve usability with negligible impact on performance or code readability

**Comment by CrockAgile** [comment]
@snewt Would it be too slick/hacky to sidestep this issue by honoring BNF comments? If BNF comments are from `;` to the end of line, then essentially they become optional. And would support comments in the input string.

**Comment by snewt** [comment]
@CrockAgile I'm not sure that would really sidestep the issue as it stands. It could be that we add support for `;` comments but as it is they are expected to only show up in specific instances.

**Comment by CrockAgile** [comment]
@snewt Sounds good! I think I got confused anyway by glancing at the algol example in the history section on the wiki.

**Comment by snewt** [comment]
closed by [21338d3](https://github.com/snewt/bnf/commit/21338d3b66f6876b7822545b2225ed3399268473)
