### ISSUE TITLE
Terminals with quotes to_string makes invalid string

### ISSUE THREAD

**Issue by CrockAgile** [snewt/bnf#30]
The current implementation of `fmt::Display` is overly simple since Terms may be parsed via `'single-quoted'` or `"double-quoted"`.

```rust
#[test]
fn quote_term_to_and_from_str() {
    let quote = Term::Terminal(String::from("\""));
    let to_string = quote.to_string(); // -> \"\"\" , uh oh, that won't do
    let from_string = Term::from_str(&to_string);
    assert_eq!(Ok(Term::Terminal(String::from("\""))), from_string);
}
```

This test fails because the current behavior of `to_string` produces a string which cannot be parsed back into the original `Terminal`.

Some solution brainstorming may help:
- `fmt::Display` could inspect if the term contains `"` to determine if output should use with single quotes
- `Term::Terminal` could be changed to a lower level enum of Single/Double quote type
- Term parsing could be changed back to not support the single quote mode, but this would remove support for grammars using terminals with double quotes

My personal gut would be the first option. It would add a few lines of complexity to `fmt::Display for Term` and make the associated `to_string` less performant, but it seems like a necessary cost. But maybe @snewt will have a cleaner idea

**Comment by snewt** [comment]
Good find!
