### ISSUE TITLE
What to do with a grammar?

### ISSUE THREAD

**Issue by CrockAgile** [snewt/bnf#7]
The example use case is parsing a bnf string to a grammar. But, what are the use cases after that?

```rust
// let input = some grammar string
let grammar = bnf::parse(input);
// now what can I do with it?
```

* Should an example be added that does something interesting by navigating the tree?
* Should any functions be added that assist in walking the tree, like a visitor pattern?
* Should the grammar be able to parse input strings and return the series of productions used?

**Comment by snewt** [comment]
I agree that there is a lot of room for growth. I'd like to begin implementing some of the things you've mentioned in the near future (or review PRs that implement them! 😊). Thanks for raising the issue.

**Comment by CrockAgile** [comment]
I was hoping that you might be able to act as the current typical user. Which of those ideas would be useful to a user? I am having trouble envisioning the end use case. But for each idea we have that resonates as useful improvement, then we should open a corresponding issue. I would rather work on features that you have deemed useful and thought out with descriptions than isolate my ideas.

**Comment by snewt** [comment]
One high priority goal I have is a `generate` function that does something along the lines of what the [erratic](https://github.com/dhconnelly/erratic) JavaScript library enables.

**Comment by CrockAgile** [comment]
I think this question has been answered by the work in 0.2.0
